FROM kaiocarvalhopravaler/php:7.2-nginx

MAINTAINER Kaio Gonçalves Carvalho

RUN echo 'fastcgi_param  NEO_CONFIG	  /opt/neo/config.php;' >> /etc/nginx/fastcgi.conf
RUN echo 'fastcgi_param  NEO_CONFIG	  /opt/neo/config.php;' >> /etc/nginx/fastcgi_params